[package]
name = "commands"
version = "0.1.0"
edition = "2021"
rust-version = "1.59"

[build-dependencies]
tauri-build = { path = "../../core/tauri-build" }

[dependencies]
tauri = { path = "../../core/tauri" }
serde = "1"
